### ISSUE TITLE
Segment中args为空时（即"args: {}"），经过parser()之后，变成"args:"，丢失了"{}"

### ISSUE THREAD

**Issue by turbe** [taofen8/salyut#1]
### 原Segment

```
- segment: 
      name: '"__test__baidunews"'
      args:  {}
      package: '"tom"'
      body: 
         - load: '"http://news.baidu.com/"'
```

### 经过parser() 方法调用后

```
- segment: 
      name: '"__test__baidunews"'
      args: 
      package: '"tom"'
      body: 
         - load: '"http://news.baidu.com/"'
```

### 可能问题：args当做属性处理

```
private static final String ATTRIBUTE_FORMAT = "%s: ";

 else if (KeyType.ATTRIBUTE.equals(keyType)){
     builder.append(String.format(ATTRIBUTE_FORMAT,tuple2.f0));
 }
```
