### ISSUE TITLE
switchtab isn't work

### ISSUE THREAD

**Issue by zly880** [taofen8/salyut#14]
when I user switchtab in my segment, I find that switchtab isn't work. I can't understard "index" .
This is my segment .  please tell me how to find my tab by index.

```yaml
- segment:
   name: '"calc"'
   args: {0: '/input'}
   body:
       #load page of Baidu
       - load: '"https://my.xiapibuy.com/Cushions-Covers-cat.26.681.9888?page=0&sortBy=sales"'
    
       - loop:
           in: {eles: 'div.shopee-search-item-result__items div.shopee-search-item-result__item'}
           each:
             - select: {path: '/tmp/url',under: '$e',ele: 'a[data-sqe=link]',attr: '"href"'}
             - put: {path: '/urls',value: '"window.open(\"" + $/tmp/url + "\")"'}
             - put: {path: '/tmp/count',value: '$i'}
             - echo: '$/urls'
             - js: '$/urls'
             - wait: {type: '"time"',millis: '4000'}
             - switchtemptab: {index: '1'}
             - wait: {type: '"presence"',ele: 'button.btn-solid-primary',timeout: '10000'}
             - find: {ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card> div.flex.flex-auto > div > div > div:nth-child(1) > div'}
             - if: '$1'
             - then:
                 - select: {ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card> div.flex.flex-auto > div > div > div:nth-child(1) > div',path: '/tmp/rank'}
                 - contains: {path: '/tmp/rank',search: '"RM"'}
                 - if: '$1'
                 - then:
                     - put: {path: '/tmp/rank',value: '"无评分"'}
             - else:
                 - put: {path: '/tmp/rank',value: '"无评分"'}
             - find: {ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card> div.flex.flex-auto > div > div > div:nth-child(3) > div:nth-child(1)'}
             - if: '$1'
             - then:
                 - select: {path: '/tmp/sale',ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card> div.flex.flex-auto > div > div > div:nth-child(3) > div:nth-child(1)'}
             - else:
                 - put: {path: '/tmp/sale',value: '"无"'}
             - find: {ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card> div.flex.flex-auto > div > div > div:nth-child(2) > div:nth-child(1)'}
             - if: '$1'
             - then:
                 - select: {path: '/tmp/rant',ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card> div.flex.flex-auto > div > div > div:nth-child(2) > div:nth-child(1)'}
             - else:
                 - put: {path: '/tmp/rant',value: '"无"'}
             - find: {ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card > div.flex.flex-auto > div > div:nth-child(3) > div > div > div > div > div.flex.items-center > div:nth-child(1)'}
             - if: '$1'
             - then:
                 - select: {path: '/tmp/price',ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card > div.flex.flex-auto > div > div:nth-child(3) > div > div > div > div > div.flex.items-center > div:nth-child(1)'}
             - else: 
                 - put: {path: '/tmp/price',value: '"无售价"'}
             - find: {ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card > div.flex.flex-auto > div > div > span'}
             - if: '$1'
             - then:
                - select: {path: '/tmp/title',ele: '#main > div > div.shopee-page-wrapper > div.page-product > div.container > div.product-briefing.flex.card > div.flex.flex-auto > div > div > span'}
             - else:
                 - put: {path: '/tmp/title',value: '"未获取到"'}
             - put: {path: '/R/list[-1]',value: '$/tmp'}
             - remove: {path: '/tmp'}
             - closetemptab:
       - export: {type: '"excel"',path: '/R/list/',value: 'count,title,price,sale,rank,rant,url'}
       - return: '$/R'
#call the segment named 'calc' and pass the argument '1+1'
- callin: {seg: '"calc"', 0: '1+1'}
- echo: '$1'   
```
