### ISSUE TITLE
loop内使用if  then continue死循环

### ISSUE THREAD

**Issue by kly402023688** [taofen8/salyut#19]
```yaml
# 以下是一个打开页面的segment, 请注意以下注释的注意点
- segment:
    name: '"new_animation_update_time"'
    package: '"Kiva"'
    args: {0: '/url'}
    body:
        - load: '$/url'
        - loop:
            in: { eles: '.tl-day' }
            each:
                - select: { ele: '$e', attr: '"class"', path: '/clazz' }
                - if: '$/clazz == "tl-day today"'
                - then:
                    - put: { path: '/todayIndex', value: '$i', lambda: 'x -> return Number(x)' }
                    - break:
        - echo: '"todayIndex: " + $/todayIndex'        
        - loop:
            in: { eles: '.season-timeline' }
            each:
                - echo: '"i:" + $i'
                - echo: '$/todayIndex'
                - if: '$i < $/todayIndex'
                - then:
                    - continue:
                - put: { path: '/index', value: '$i'}
                - echo: '"else:" + $/index'
                - select: { eles: '.season-group:not(.season-timer)', under: '$e', path: '/groupList' }
#                 - loop:
#                     in: { values: '$/groupList', mutable: '$false' }
#                     each:
#                         - select: { ele: '.group-time', under: '$e', path: '/time' }
#                         - select: { eles: '.season-item', under: '$e', path: '/items' }
#                         - put: { path: '/head', value: '$/headList[$/index]'}
#                         - select: { ele: '.t-date', under: '$/head', path: '/date' }
#                         - select: { ele: '.t-week', under: '$/head', path: '/week' }
#                         - echo: '$/date'
#                         - loop:
#                             in: { values: '$/items', mutable: '$false' }
#                             each:
#                                 - select: { ele: 'img', attr: 'src', under: '$v', path: '/item/pic' }
#                                 - select: { ele: '.season-title', under: '$v', path: '/item/title' }
#                                 - select: { ele: '.season-desc', under: '$v', path: '/item/desc' }
#                                 - put: { path: '/item/date', value: '$/date' }
#                                 - put: { path: '/item/week', value: '$/week'}
#                                 - put: { path: '/resList[-1]', value: '$/item' }
        - return: '$/resList'

- segment:
    name: '"__test__new_animation_update_time"'
    package: '"Kiva"'
    body:
        - callin: {seg: '"new_animation_update_time"', 0: '"https://www.bilibili.com/anime/timeline"', package: '"Kiva"'}
        - echo: '$1'
        
# 在trico后台要提交segment的时候，请将以下这一行的callin注释掉。
- callin: {seg: '"__test__new_animation_update_time"', package: '"Kiva"'}
```
