### ISSUE TITLE
Segment解析后格式化问题

### ISSUE THREAD

**Issue by turbe** [taofen8/salyut#2]
**name前面有6个空格占位，formatYaml此方法中， builder.append(lines[i]); 去掉lines[i]原有空格**

```
private static String formatYaml(String yamlString){
        StringBuilder builder = new StringBuilder();
        String[] lines = yamlString.split("\n");
        builder.append(lines[0]);
        builder.append("\n");
        for(int i = 1; i < lines.length; i++){
            builder.append("    ");
            builder.append(lines[i]);
            builder.append("\n");
        }
        return builder.toString();
    }
```

 **STANDARD_IDENT 应该为4个空格占位，以下代码中只有3个占位。**

`private static final String STANDARD_IDENT = "   ";`

**最后结果**

```
- segment: 
      name: '"__test__baidunews"'
      args: 
      package: '"tom"'
      body: 
         - load: '"http://news.baidu.com/"'
         - select: { eles: '.ulist li',path: '/arr' }
         - len: '$/arr'
         - if: '$1 > 0'
         - then: 
            - return: '$true'
         - else: 
            - return: '$false'
```

private static final String STANDARD_IDENT = "   ";
