### ISSUE TITLE
提交代码后脚本格式化问题

### ISSUE THREAD

**Issue by turbe** [taofen8/salyut#25]
- segment下级name、body等标签有8个空格缩进，以及- loop:下级in、each等标签也有8个空格缩进

如下代码

```
- segment: 
        package: '"taobaoSearch"'
        name: '"pailitaoSearchPic"'
        args: { 0: '/url',1: '/isTest',2: '/img',3: '/buyingId' }
        body: 
            - loop: 
                    in: { eles: '#imgsearch-itemlist .item',mutable: '$false' }
                    each: 
```
