### ISSUE TITLE
使用mobile标签出现不停重启浏览器

### ISSUE THREAD

**Issue by turbe** [taofen8/salyut#26]
使用mobile标签后运行脚本出现不停重启浏览器，如

```
- segment: 
        name: '"taobaoItemDescTest"'
        package: '"aichuanda"'
        args: { 0: '/test' }
        body: 
            - mobile:
            - load: '"https://main.m.taobao.com/index.html"'
```
