### ISSUE TITLE
callin标签中key与value之间没有空格，报空指针，kernel没有抛出异常

### ISSUE THREAD

**Issue by turbe** [taofen8/salyut#29]
callin标签中key与value之间没有空格，报空指针，kernel没有抛出异常，导致IDE一直处于running状态。卡住的假象。
示例代码(0:'"test"'之前没有空格)
```
- segment:
    # 特别注意testSegment的入口名必须是以“__test__”开头,(您也可以写多个Segment通过其中callin来进行调用)
    name: '"__test__appEdu"'
    package: '"school"'
    args: {}
    body:
        - callin: {seg: '"appEdu"', package: '"school"', 0:'"test"', 1: '"https://www.app.edu.gov.on.ca/eng/sift/schoolProfile.asp?SCH_NUMBER=000779"', 2: '"000779"', 3: '"Elementary"' }
        - put: {path: '/test', value: '$1'}
        - echo: '$/test'
        - if: '$/test != $null'
        - then: 
            - return: '$true'
        - else:
            - return: '$false'
```

kernel报错信息

```
1589967087774	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/43/6g6jmkbj2qg6zy1cn_pqqmww0000gp/T/rust_mozprofileLq211j"
1589967088115	addons.webextension.doh-rollout@mozilla.org	WARN	Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1589967088325	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1589967088325	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1589967088325	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1589967088325	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1589967090030	Marionette	INFO	Listening on port 61627
1589967090137	Marionette	WARN	TLS certificate errors will be ignored for this session
五月 20, 2020 5:31:30 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: W3C
2020-05-20 17:31:31,618 [release] - java.lang.NullPointerException
```
