### ISSUE TITLE
yaml语法错误时，报了空指针, 没有捕获异常并返回控制台

### ISSUE THREAD

**Issue by turbe** [taofen8/salyut#3]
**错误语法示例**

```
                - if: '($i+1)%6==0'
                - then:
                    - js: '"document.documentElement.scrollTop =  438;"'
                    - wait: { type: '"time"', millis: '1500'}
                - else:
                - then:
                    - echo: '"is wrong!!!"'
```

**salyut exception**

`2020-04-08 23:54:35,645 [release] - java.lang.NullPointerException`
