### ISSUE TITLE
遍历调用带有参数的Segment，均执行第一次调用的Segment的参数

### ISSUE THREAD

**Issue by turbe** [taofen8/salyut#31]
segment 参数一直保留着第一次传进去的值

部分示例如下：
```
- segment:
    package: '"school"'
    name: '"getReportCardData"'
    args: {}
    body:
        - loop:
            in: {eles: '.row table#insidetable2', mutable: '$false'}
            each:
                - select: { ele: 'caption', under: '$e', path: '/indexType'}
                - echo: '$/indexType'
                - put: { path: '/index', value: '$i'}
                - js: '""'
                - callin: {package: '"school"', seg: '"getTableData"', 0: '$/indexType', 1: '$/index'}
                - put: {path: '/cardTableList', value: '$1'}
                - if: '$/cardTableList != $null'
                - then:
                    - loop:
                        in: { values: '$/cardTableList'}
                        each:
                            - copy: { path: '/reportCardList[-1]', value: '$v'} # $V循环非web element元素的数组元素值
        - return: '$/reportCardList'


- segment:
    package: '"school"'
    name: '"getTableData"'
    args: { 0: '/indexType', 1: '/index'}
    body:
        - echo: '"indexType="+$/indexType'
        - echo: '"getTableData="+$/index'
        - if: '$/index == 0'
        - then:
            - loop:
                in: { eles: 'tbody#tbody_0 tr', mutable: '$false'}
                each:
                    - if: '$i>1'
                    - then:
                        - put: { path: '/tableRow/indexType', value: '$/indexType'}
                        - select: { path: '/tableRow/indexDesc', ele: 'td:nth-child(1)', under: '$e'}
                        - select: { path: '/tableRow/school', ele: 'td:nth-child(2)', under: '$e'}
                        - select: { path: '/tableRow/englishStudents', ele: 'td:nth-child(3)', under: '$e'}
                        - select: { path: '/tableRow/frenchStudents', ele: 'td:nth-child(4)', under: '$e'}
                        - put: { path: '/tableList[-1]', value: '$/tableRow'}
                        - remove: { path: '/tableRow'}
            - return: '$/tableList'
        - if: '$/index == 1'
        - then:
            - loop:
                in: { eles: 'tbody#tbody_1 tr', mutable: '$false'}
                each:
                    - if: '$i>1'
                    - then:
                        - put: { path: '/tableRow/indexType', value: '$/indexType'}
                        - select: { path: '/tableRow/indexDesc', ele: 'td:nth-child(1)', under: '$e'}
                        - select: { path: '/tableRow/school', ele: 'td:nth-child(2)', under: '$e'}
                        - select: { path: '/tableRow/englishStudents', ele: 'td:nth-child(3)', under: '$e'}
                        - select: { path: '/tableRow/frenchStudents', ele: 'td:nth-child(4)', under: '$e'}
                        - put: { path: '/tableList[-1]', value: '$/tableRow'}
                        - remove: { path: '/tableRow'}
            - return: '$/tableList'
        - if: '$/index == 2'
        - then:
            - loop:
                in: { eles: 'tbody#tbody_2 tr', mutable: '$false'}
                each:
                    - if: '$i>1'
                    - then:
                        - put: { path: '/tableRow/indexType', value: '$/indexType'}
                        - select: { path: '/tableRow/indexDesc', ele: 'td:nth-child(1)', under: '$e'}
                        - select: { path: '/tableRow/school', ele: 'td:nth-child(2)', under: '$e'}
                        - select: { path: '/tableRow/englishStudents', ele: 'td:nth-child(3)', under: '$e'}
                        - select: { path: '/tableRow/frenchStudents', ele: 'td:nth-child(3)', under: '$e'}
                        - put: { path: '/tableList[-1]', value: '$/tableRow'}
                        - remove: { path: '/tableRow'}
            - return: '$/tableList'            

```
